AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  VoiceChain_backend

Parameters:
  TableUsers:
    Type: String
    Default: "VC_users"
    Description: store connection identifiers for each connected clients
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: "Required. Can be characters and underscore only. No numbers or special characters allowed."

Resources:
  VoiceChainSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: VoiceChainSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.message"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VoiceChainSocket
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VoiceChainSocket
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VoiceChainSocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VoiceChainSocket
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations
  BroadcastRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VoiceChainSocket
      RouteKey: broadcast
      AuthorizationType: NONE
      OperationName: BroadcastRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref BroadcastInteg
  BroadcastInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VoiceChainSocket
      Description: Broadcast Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BroadcastFunction.Arn}/invocations
  OnceRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VoiceChainSocket
      RouteKey: once
      AuthorizationType: NONE
      OperationName: OnceRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OnceInteg
  OnceInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VoiceChainSocket
      Description: once Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnceFunction.Arn}/invocations

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - BroadcastRoute
      - DisconnectRoute
      - OnceRoute
    Properties:
      ApiId: !Ref VoiceChainSocket
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref VoiceChainSocket

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "connectionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "connectionId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref TableUsers

  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: onconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_USERS: !Ref TableUsers
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableUsers
  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - VoiceChainSocket
      - OnConnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ondisconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_USERS: !Ref TableUsers
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableUsers
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - VoiceChainSocket
      - OnDisconnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com
  BroadcastFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: broadcast/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_USERS: !Ref TableUsers
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableUsers
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VoiceChainSocket}/*"
  BroadcastPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - VoiceChainSocket
      - BroadcastFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BroadcastFunction
      Principal: apigateway.amazonaws.com
  OnceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: once/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_USERS: !Ref TableUsers
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableUsers
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VoiceChainSocket}/*"
  OncePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - VoiceChainSocket
      - OnceFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnceFunction
      Principal: apigateway.amazonaws.com

Outputs:
  ConnectionsTableArn:
    Description: "Connections table ARN"
    Value: !GetAtt ConnectionsTable.Arn

  OnConnectFunctionArn:
    Description: "OnConnect function ARN"
    Value: !GetAtt OnConnectFunction.Arn

  OnDisconnectFunctionArn:
    Description: "OnDisconnect function ARN"
    Value: !GetAtt OnDisconnectFunction.Arn

  BroadcastFunctionArn:
    Description: "Broadcast function ARN"
    Value: !GetAtt BroadcastFunction.Arn

  OnceFunctionArn:
    Description: "Once function ARN"
    Value: !GetAtt OnceFunction.Arn

  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value:
      !Join [
        "",
        [
          "wss://",
          !Ref VoiceChainSocket,
          ".execute-api.",
          !Ref "AWS::Region",
          ".amazonaws.com/",
          !Ref "Stage",
        ],
      ]
